### ISSUE TITLE
ValueError: data must be 2 dimensional

### ISSUE THREAD

**Issue by erjel** [Kapoorlabs-CAPED/NapaTrackMater#1]
Hi @kapoorlab ,

I saw your announcement in the [image.sc forum](https://forum.image.sc/t/trackmate-track-viewer-in-napari/47645), and the combination of napari + TrackMate sounds just perfect for my purposes. Thank you for sharing the code and providing a pip package!

For a quick test, I started with your example [notebook](https://github.com/kapoorlab/NapaTrackMater/blob/main/TrackMateVisualization.ipynb) and changed the `path_xml` and `SegmentationImage` paths according to my file locations and set `RawImage` as well as `MaskImage` to `None`.

When I now continue in the notebook, it correctly creates the "Tracklets", but once it starts to compute them for TrackID `0` the following error message appears:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-23-8a4f94a8c1bd> in <module>
----> 1 RegionID, VolumeID, locationID, Tracks, ID, StartID = TM.ImportTrackmateXML(
      2     path_xml,Seg,
      3     image = Raw,
      4     Mask = Mask,
      5     XYcalibration = XYcalibration,

C:\ProgramData\Anaconda3\envs\napatrackmater\lib\site-packages\napatrackmater\Trackmate.py in ImportTrackmateXML(xml_path, Segimage, XYcalibration, Zcalibration, Tcalibration, image, Mask, mintracklength)
    535 
    536                                                    TwoDCoordinates = [(prop.centroid[1] , prop.centroid[2]) for prop in properties]
--> 537                                                    TwoDtree = spatial.cKDTree(TwoDCoordinates)
    538                                                    TwoDLocation = (y ,x)
    539                                                    closestpoint = TwoDtree.query(TwoDLocation)

ckdtree.pyx in scipy.spatial.ckdtree.cKDTree.__init__()

ValueError: data must be 2 dimensions
```

~~In trackmate I used a series of 3D images. You can find the trackmate xml file as well the segmentation results at:
https://datashare.mpcdf.mpg.de/s/AtEPeYkTtdlnBOi~~

**Comment by kapoorlab** [comment]
Ah I see, thanks for trying the package and sending me the data. In this notebook it is expecting to find an image of shape TZYX so you would have to stitch your timepoints to make one large file which then corresponds to the xml file that you get from TrackMate. Then it should work as expected. 

Maybe you could make a cell in the notebook where it creates a numpy array after reading the sequence of images from the folder? If you already did that then this problem could be coming from the stacks where there are no cells hence TwoDCoordinates is just None. I will build an exception to catch that and let you know when the new package is available with that change. Thanks again.

**Comment by erjel** [comment]
> [..] In this notebook it is expecting to find an image of shape TZYX so you would have to stitch your timepoints to make one large file which then corresponds to the xml file that you get from TrackMate. Then it should work as expected. 

Thank you for your quick reply, I scrolled a little in your code and relized this as well. I created a numpy array with a 2x (x, y, z) downscaled version of the segmentation results (I took the same approach to reduce the memory footprint in TrackMate). 

Now the Tracklets are correctly calcualted!

Unfortunately, another error occured:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-8a4f94a8c1bd> in <module>
     11 scale = [1,2,1,1]
     12 totaltracks = len(Tracks)
---> 13 TM.TrackMateLiveTracks(Raw, None, Mask,savedir, scale, locationID, RegionID, VolumeID, ID, StartID, Tcalibration)

~\miniconda3\envs\napatrackmater\lib\site-packages\napatrackmater\Trackmate.py in TrackMateLiveTracks(Raw, Seg, Mask, savedir, scale, locationID, RegionID, VolumeID, ID, StartID, Tcalibration)
    934         UpdateMask = Mask
    935 
--> 936     Boundary = GetBorderMask(UpdateMask.copy())
    937 
    938     with napari.gui_qt():

AttributeError: 'NoneType' object has no attribute 'copy'

```

Best wishes,

Eric

**Comment by kapoorlab** [comment]
Hi Eric, 

Thanks for pointing this out too, for now to avoid this could you please change these lines in the notebook
```
if MaskImage is not None:
    Mask = imread(MaskImage)
else:
    Mask = None
```
to the lines below where you provide a rectangular region as a mask excluding 50 (or some other value) pixels around the border.
```
if MaskImage is not None:
    Mask = imread(MaskImage)
else:
    Mask = None
    Mask = np.zeros_like(Seg) 
    Mask[:,:, 50:Mask.shape[2]-50, 50:Mask.shape[3]-50] = 1
```
I will update the code to incorporate these two issues very soon.

**Comment by erjel** [comment]
It works now! Thank you for your help!

Two comments:
```
Mask[:,:, 50:Mask.shape[2]-50, 50:Mask.shape[3]-50] = 1
```
can be written
```
Mask[:,:, 50:-50, 50:-50] = 1
```
and I used 

```
RegionID, VolumeID, locationID, Tracks, ID, StartID = TM.ImportTrackmateXML(
    path_xml,Seg,
    image = Raw,
    Mask = None,
    XYcalibration = XYcalibration,
    Zcalibration = Zcalibration
    , Tcalibration = Tcalibration,
    mintracklength = mintracklength)
```

Because otherwise the import of the xml file takes quite long (I did not wait until it finished).

Best wishes,

Eric
