### ISSUE TITLE
Cannot start plugin: ModuleNotFoundError: No module named 'cellshape_cloud'

### ISSUE THREAD

**Issue by maulakhan** [Kapoorlabs-CAPED/NapaTrackMater#33]
Dear all,

I can install the `napatrackmate` plugin through napari successfully but when I start the plugin I get this error:
```
\miniconda3\envs\napari\lib\site-packages\vollseg_napari_trackmate\_widget.py in plugin_wrapper_track()
     27 def plugin_wrapper_track():
     28
---> 29     from cellshape_cloud import CloudAutoEncoder
        global cellshape_cloud = undefined
        global CloudAutoEncoder = undefined
     30     from cellshape_cluster import DeepEmbeddedClustering
     31     from napatrackmater import load_json

ModuleNotFoundError: No module named 'cellshape_cloud'
```

Even if i do `pip install cellshape_clould`, it throws other errors

Can you please help me?

**Comment by kapoorlab** [comment]
Yes this is happening because after my PR's that I made to cellshape-helper and cellshape-cloud a new version has not been released on Pypi yet: [Request for new release](https://github.com/Sentinal4D/cellshape-cloud/issues/14). Till @DeVriesMatt carves a new release you can clone my forks and install them in your virtual environment using ``` pip install -e . ``` My forks are here: [cellshape helper](https://github.com/kapoorlab/cellshape-helper) and [cellshape cloud](https://github.com/kapoorlab/cellshape-cloud), after you install these then launching the Napari plugin from the environment would work.

**Comment by DeVriesMatt** [comment]
Hi both, I'm sorry about this. I will make a new release asap! There were just some formatting issues that needed fixing.

**Comment by sebgoti** [comment]
Hi there, I installed both forks as suggested by @kapoorlab and when trying to open the plugin I had the following error:

```
~/opt/anaconda3/envs/napari_env/lib/python3.8/site-packages/vollseg_napari_trackmate/_widget.py in plugin_wrapper_track()
     28
     29     from cellshape_cloud import CloudAutoEncoder
---> 30     from cellshape_cluster import DeepEmbeddedClustering
        global cellshape_cluster = undefined
        global DeepEmbeddedClustering = undefined
     31     from napatrackmater import load_json
     32     from napatrackmater.pretrained import (

ModuleNotFoundError: No module named 'cellshape_cluster'
```

**Comment by kapoorlab** [comment]
@sebgoti Ah can you please also install this fork of mine and then it will load the missing module: [cellshape-cluster kapoorlabs fork](https://github.com/kapoorlab/cellshape-cluster)

**Comment by sebgoti** [comment]
It works but you might want to update the `requirements.txt` since I still got a couple of errors regarding `lmfit` and `perfmetrics` not being installed.

**Comment by kapoorlab** [comment]
Thanks, I removed the old file that was requiring those as dependencies, I will also update the package from using `setup.py` to `setup.cfg` file as we do not use `requirements.txt` anymore. Another item in the list would be to upload the pytorch models in the format required by this plugin to run, till then you can run the plugin without obtaining the cell shape cluster class plots.
