### ISSUE TITLE
Can't run NapaTrackMater

### ISSUE THREAD

**Issue by simonguld** [Kapoorlabs-CAPED/NapaTrackMater#39]
Hi guys,

I am trying to use NapaTrackmater, but when I import it, I get the following error:

```
File "C:\Users\Simon Andersen\AppData\Roaming\Python\Python39\site-packages\kapoorlabs_lightning\lightning_trainer.py", line 626, in ClusterLightningDistModel
    def predict_step(self, batch, batch_idx) -> STEP_OUTPUT | None:
TypeError: unsupported operand type(s) for |: '_UnionGenericAlias' and 'NoneType'
```

Since you have also made the lightning package, I figure this is the place to ask for help.

Greetings from Denmark
Simon

**Comment by kapoorlab** [comment]
Hello,

I looked at it from my side and it could be that your lightning version is latest one, so I updated my setup.py file and released a new version for napatrackmater (3.7.9), could you try again and see if it works with this version, the lightning version that is needed is >=2.0.4.

Cheers,
Varun

**Comment by simonguld** [comment]
Hi Varun, 

I tried reinstalling napatrackmater again using 
1) python -m pip --user napatrackmater,
and when that didn't work, I cloned the git repo and used
2) pip install --user -e .

None worked. The kapoorlabs-lightning version is 5.2.8.

Below is the full error message:

```
Traceback (most recent call last):
  File "C:\Users\Simon Andersen\Projects\Projects\CellSegmentationTracking\napari_trackmate.py", line 2, in <module>
    import napatrackmater
  File "c:\users\simon andersen\napatrackmater\napatrackmater\__init__.py", line 2, in <module>
    from .Trackmate import *
  File "c:\users\simon andersen\napatrackmater\napatrackmater\Trackmate.py", line 17, in <module>
    from .clustering import Clustering
  File "c:\users\simon andersen\napatrackmater\napatrackmater\clustering.py", line 1, in <module>
    from kapoorlabs_lightning.lightning_trainer import AutoLightningModel
  File "C:\Users\Simon Andersen\miniconda3\envs\cellpose\lib\site-packages\kapoorlabs_lightning\__init__.py", line 6, in <module>
    from .lightning_trainer import (
  File "C:\Users\Simon Andersen\miniconda3\envs\cellpose\lib\site-packages\kapoorlabs_lightning\lightning_trainer.py", line 519, in <module>
    class ClusterLightningDistModel(LightningModule):
  File "C:\Users\Simon Andersen\miniconda3\envs\cellpose\lib\site-packages\kapoorlabs_lightning\lightning_trainer.py", line 626, in ClusterLightningDistModel
    def predict_step(self, batch, batch_idx) -> STEP_OUTPUT | None:
TypeError: unsupported operand type(s) for |: '_UnionGenericAlias' and 'NoneType'
```

Do you have any ideas on how to proceed?

Best regards,
Simon

**Comment by kapoorlab** [comment]
I will look into it this week as I am updating some internal functions this week and will get back to you after that, maybe doing that would resolve this issue as well.

**Comment by simonguld** [comment]
Thank you so much, Kapoor!

**Comment by kapoorlab** [comment]
Hello @simonguld, I just released a new version post updates. Can you run this command:

`pip install napatrackmater --ignore-installed`

and see if it works for you now?

**Comment by simonguld** [comment]
Now it works! Thanks a lot, Kapoor.

On a different note: I can't find an example of how to generate the NapaTrackMater master XML. I suspect I need the TrackMate class, but it takes a bunch of arguments (like spot, track and edge csv files) that I seemingly can't generate using the Fiji GUI with TrackMate. 
Do you have a Notebook showing how to do this?

Thank you for all your help

Best regards,
Simon

**Comment by kapoorlab** [comment]
Hi Simon, Great that it works for you, this allows you to input the xml file of TrackMate with the spots, tracks and edges csv into the plugin to visualize dividing/non-dividing tracks separately or together and color tracks with track attributes, or color cells with spot or track attributes, you also get histogram and line plots for doing your analysis. That is what I call free tier.

The master XML file is generated in the plugin or using our scripts that we have for our collaborators that uses a trained autoencoder model to convert the segmentation labels into point clouds and then we compute additional track and spot attributes from that and also including a tissue segmentation image in 2D or as 3D + time. Currently we do not have any public scripts, models or training data. But if you choose to be our paid collaborator we can generate it for you. 

The TrackMate GUI allows you to export tracks as xml and csv files of spots, tracks and edges in TrackMate  version > 7.0.0. You can ask @tinevez for help on Image sc forum regarding saving the XML and the related csv files but it is not that tricky.

Hope it helps, I will close the issue of installation 
Cheers,
Varun
