### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by NicolasCARPi** [Kapoorlabs-CAPED/NapaTrackMater#7]
So I'm trying to run the BTrackMateVisualization notebook and I'm running into memory issue.

My computer has 16 Gb of RAM and 8 Gb of swap, and I run out of memory.

If I run a profiler, the steps where it reads the images already takes 10 Gb of memory. And we didn't even start any computation at this point.

Is it necessary to read Raw as float16?

I am not sure what could be a good solution here. Splitting the example image in half? On one hand it's good to provide a full working example, on the other hand if one needs 32 Gb of RAM to run it, it might be limitating.

Another solution would be to read only the frame of interest when needed, and not load the full file in memory, if that's at all possible. You know best the intricacies of the software, so let me know what you think would be possible to do.

**If we look at import_TM_XML, we can see that it really only needs the shape of the image, not the full image, so maybe provide that as parameters to the function instead of the full image**, this way the full image can be discarded once we have its shape and we can free up memory.

**Comment by kapoorlab** [comment]
By default the visualization program takes in all three images the Raw, Segmentation in the same dimension and allows the mask image to be 1 dimension less (internally it converts the lower dimension mask to be the same as others), for the import_TM_XML function you only need the shape and for displaying the tracks on the image in the next cell functions you need the Raw, Segmentation and the Mask but only for visualization purposes the images imported do not have to be float 16 indeed and can be just uint8. 

I can also try to load these large images as a dask array than a numpy array to see if that helps.

**Comment by NicolasCARPi** [comment]
If dask can help with size in memory reduction, it would be a great improvement indeed.

This documentation seems on point: https://napari.org/tutorials/applications/dask.html

**Comment by kapoorlab** [comment]
I tried a simple image read of shape TZYX shape with dask and it messed up the image shape

```
from dask_image.imread import imread
import dask.array as da

ImageName = 'data/Raw.tif'

image = imread(ImageName)
stack = da.stack(image)
stack.shape  # should be (190,31,512,712)

```

but it is now (5890, 512, 712), is there a way to know the image shape without reading it from file?

**Comment by NicolasCARPi** [comment]
>  is there a way to know the image shape without reading it from file?

Yes, read it, extract the shape and discard it!

~~~python
Raw = imread(RawImage)
shape = Raw.shape
Raw = None # <- this will free it up from memory
~~~

And then you pass the shape to your function that needs it. It's always a good practice to pass to a function the bare minimum it needs (and for a function to do only one thing).

Note that even on my home computer with 32 Gb of RAM and 16 Gb of swap, I could only get to 84% before the process was killed by the kernel.

![2021-05-11-230716_838x121_scrot](https://user-images.githubusercontent.com/3043706/117885716-7613e100-b2ae-11eb-920a-b030df03a27f.png)

**Comment by kapoorlab** [comment]
Ah, I am still working on dask arrays but when I try to read a label image they totally misread the image dimensions, this can not even be possible right!

```
from tifffile import imread
from dask_image.imread import imread as daskread
LabelName = 'data/Seg.tif'
y = imread(LabelName)
x = daskread(LabelName)
print(x.shape, y.shape)
```
It prints:
(1, 512, 712) (190, 31, 512, 712)

for an image that has 190 timepoints, 31 Z and other dimensions as X and Y

**Comment by sofroniewn** [comment]
Note sure if this is completely relevant to the issue at hand here, but we're going to be changing the default settings of our dask cache in the next release, see here https://github.com/napari/napari/pull/2590. That might help memory issues

**Comment by kapoorlab** [comment]
I think here the issue is not memory related, it is reading a float 32 image properly 

```
from tifffile import imread
from dask_image.imread import imread as daskread
import dask as da
LabelName = 'data/Raw.tif'
y = imread(LabelName)
x = daskread(LabelName)
print(x.shape, y.shape)
x = da.array.reshape(x, y.shape)
print(x.shape)
```
Output: 
(5890, 512, 712) (190, 31, 512, 712)
(190, 31, 512, 712)
as expected but if I try to do the same for the segmentation image of this image I get the result output of before.

**Comment by NicolasCARPi** [comment]
@sofroniewn Thanks for the info! I don't think it's relevant here but as we are dealing with bigger and bigger images these kind of changes are most welcome!

@kapoorlab not sure what's happening here, but pretty sure you won't go to sleep until you find the problem :p

**Comment by GenevieveBuckley** [comment]
> Ah, I am still working on dask arrays but when I try to read a label image they totally misread the image dimensions, this can not even be possible right!
> 
> ```
> from tifffile import imread
> from dask_image.imread import imread as daskread
> LabelName = 'data/Seg.tif'
> y = imread(LabelName)
> x = daskread(LabelName)
> print(x.shape, y.shape)
> ```
> 
> It prints:
> (1, 512, 712) (190, 31, 512, 712)
> 
> for an image that has 190 timepoints, 31 Z and other dimensions as X and Y

Copying the conversation from image.sc here too: https://forum.image.sc/t/dask-array-strange-behaviour-for-label-images/52666

> So, dask-image calls out to the pims library and pims needs a `bundle_axes` keyword argument to properly show more than just the xy dimensions
>
> http://soft-matter.github.io/pims/v0.5/multidimensional.html
>
> The first thing I’d try is to pass in a `bundle_axes` keyword argument through your dask-image imread call and see if that works.
>
> The second easiest option might be to try the `imread` function that lives in dask itself (not dask-image): `dask.image.imread()` [API — Dask documentation](https://docs.dask.org/en/latest/array-api.html?highlight=image#image-support) (this function pre-dates the dask-image library. By default it will use the scikit-image imread function rather than pims, but you can also pass in your own desired imread function - like tifffile.imread)

**Comment by GenevieveBuckley** [comment]
> I think here the issue is not memory related, it is reading a float 32 image properly

Ok, well that's very weird

**Comment by kapoorlab** [comment]
@NicolasCARPi I tried the BTrackMateLocalization notebook with dask array imread  and memeory wise there was not much improvement but the runtime was order of magnitude slower than with just tifffile imread so I am keeping the tiffile imread whem making the csv file in that notebook. Now am checking the notebook you have problems with to see if dask array help there.

**Comment by kapoorlab** [comment]
@NicolasCARPi hi again, I made memory related changes and added dask array and dask delayed operations and tested it on my Mac, for the provided tracking example my computer memory tops to about 10G now. Making a PR for you to test, I updated the requirements file with the dask dependency. And yes, no sleeping for me :), searching for a new problem now haha.
